name: bohurupi_cms
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  font_awesome_flutter: ^10.7.0
  pull_to_refresh: ^2.0.0
  animated_background: ^2.0.0
  package_info_plus: ^8.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bohurupi_login_logo.png
    - assets/bohurupi_logo.png
    - assets/Bohurupi-Icon.png
    - assets/default_avatar.png
